"""fresh db

Revision ID: 267d90547b9b
Revises: 
Create Date: 2020-02-04 15:42:34.167028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267d90547b9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('canFeed', sa.Integer(), nullable=True),
    sa.Column('canView', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=True),
    sa.Column('scheduleFeed', sa.Integer(), nullable=True),
    sa.Column('feedDays', sa.Integer(), nullable=True),
    sa.Column('feedHour', sa.Integer(), nullable=True),
    sa.Column('feedMinute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attributes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
