"""attr table

Revision ID: 4d326f93bac4
Revises: 
Create Date: 2020-01-20 11:32:26.902716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d326f93bac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.add_column('attributes', sa.Column('userID', sa.Integer(), nullable=True))
    op.alter_column('attributes', 'canFeed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attributes', 'canView',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attributes', 'style',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'attributes', 'users', ['userID'], ['id'])
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.alter_column('attributes', 'style',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('attributes', 'canView',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attributes', 'canFeed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('attributes', 'userID')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
